-- MySQL Script generated by MySQL Workbench
-- seg 21 set 2020 18:54:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pignus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pignus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pignus` ;
USE `pignus` ;

-- -----------------------------------------------------
-- Table `pignus`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pignus`.`user` ;

CREATE TABLE IF NOT EXISTS `pignus`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`username` ASC))
ENGINE = InnoDB;

INSERT
INTO `pignus`.`user`(username, password)
VALUES ('admin', 'admin');

-- -----------------------------------------------------
-- Table `pignus`.`incident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pignus`.`incident` ;

CREATE TABLE IF NOT EXISTS `pignus`.`incident` (
  `idincident` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `chance` FLOAT NOT NULL,
  `photo_path` VARCHAR(45) NOT NULL,
  `original_photo_path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idincident`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pignus`.`telegramBotUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pignus`.`telegramBotUser` ;

CREATE TABLE IF NOT EXISTS `pignus`.`telegramBotUser` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `chatId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
